### ISSUE TITLE
Set up CI with github actions

### ISSUE THREAD

**Issue by jitinsharma** [jitinsharma/android-conferences#3]

**Comment by ch8n** [comment]
hi @jitinsharma  I will love to work on this, please let me know what all things you want to include in Github actions

**Comment by jitinsharma** [comment]
Thanks @ch8n 
I think a good start would be an action which would build the project on PR and commit to master.

**Comment by ch8n** [comment]
> Thanks @ch8n
> I think a good start would be an action which would build the project on PR and commit to master.

people don't do auto-merge on PR build, you sure about this? cause any PR which passes build would be merged
